

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
# platform :ios, '8.0'

target 'SidebarDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SidebarDemo

pod 'XCDYouTubeKit'
pod 'AFJSONRPCClient'
pod 'youtube-ios-player-helper', '~> 0.1.4'
pod ‘google-cast-sdk’
pod ‘HCYoutubeParser’
pod 'AFNetworking'
pod 'AFNetworkActivityLogger'
end




